### ISSUE TITLE
one question

### ISSUE THREAD

**Issue by zhaojc001** [CR-Ko/Vehicle-Distance-Detection#1]
I run test_yolo_car_lane.py and test_yolo_video.py,it will appear the following problem,please help me:
Traceback (most recent call last):
  File "test_yolo_video.py", line 339, in <module>
    _main(parser.parse_args())
  File "test_yolo_video.py", line 293, in _main
    K.learning_phase(): 0
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1096, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (1, 608, 608, 3) for Tensor 'input_1:0', which has shape '(?, 416, 416, 3)'

**Comment by kkk324** [comment]
You should resize your image shape.
